// temas.js
export const temas = {
  natal: {
    nome: "Natal",
    corPrimaria: "#D62828",
    corSecundaria: "#FAF3F3",
    fonte: "'Merriweather', serif",
    icones: "natal",
    iconeSobreLogo: "/icones_temas/gorro-do-papai-noel.png",
    iconeEstilo: {
      top: '-8px',
      left: '-8px',
      width: '24px',
    },
  },
  festaJunina: {
    nome: "Festa Junina",
    corPrimaria: "#F97316",
    corSecundaria: "#FFF7ED",
    fonte: "'Comic Neue', cursive",
    icones: "junina",
    iconeSobreLogo: "/icones_temas/chapeu.png",
    iconeEstilo: {
      top: '-20px',
      left: '50%',
      transform: 'translateX(-50%)',
      width: '38px',
    },
  },
  geek: {
    nome: "Geek",
    corPrimaria: "#4B0082",
    corSecundaria: "#E0E0E0",
    fonte: "'Share Tech Mono', monospace",
    icones: "geek",
    iconeSobreLogo: "/icones_temas/geek.png",
    iconeEstilo: {
      top: '5px',
      left: '50%',
      transform: 'translateX(-50%)',
      width: '38px',
    },
  },
  praia: {
    nome: "Praia",
    corPrimaria: "#00B4D8",
    corSecundaria: "#CAF0F8",
    fonte: "'Baloo 2', cursive",
    icones: "praia",
    iconeSobreLogo: "/icones_temas/bola.png",
    iconeEstilo: {
      top: '0px',
      left: '50%',
      transform: 'translateX(-50%)',
      width: '38px',
    },
  },
  halloween: {
    nome: "Halloween",
    corPrimaria: "#4B0082",
    corSecundaria: "#2C2C2C",
    fonte: "'Creepster', cursive",
    icones: "halloween",
    iconeSobreLogo: "/icones_temas/chapeu_bruxa.png",
    iconeEstilo: {
      top: '-20px',
      left: '50%',
      transform: 'translateX(-50%)',
      width: '28px',
    },
  },
  floresta: {
    nome: "Floresta",
    corPrimaria: "#2E8B57",
    corSecundaria: "#F0FFF0",
    fonte: "'Roboto Slab', serif",
    icones: "floresta",
    iconeSobreLogo: "/icones_temas/galho.png",
    iconeEstilo: {
      top: '-15px',
      left: '110%',
      transform: 'translateX(-50%)',
      width: '28px',
    },
  },
};